GamerShop/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GamerShop.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        public string Description { get; set; }

        public string ImgUrl { get; set; }

        [Required]
        [Range(0, 99999)]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        
        [Display(Name = "Left in stock")]
        public int StockCount { get; set; }
    }
}

GamerShop/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GamerShop.Models;
using GamerShop.Repositories;

namespace GamerShop.Controllers
{
    [Authorize]
    public class CartItemsController : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        private ICartItemRepository repo;

        public CartItemsController(ICartItemRepository repo)
        {
            this.repo = repo;
        }


        public ActionResult Index()
        {
            return View(repo.GetAll());
        }

        [HttpPost]
        public ActionResult AddToCart(int productId)
        {
            repo.AddToCart(productId, 1);
            return RedirectToAction("Index");
        }

        // GET: CartItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = repo.Find((int)id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // GET: CartItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = repo.Find((int)id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductId = repo.GetSelectList(cartItem);
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Quantity,ProductId,CartId")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                repo.AddOrUpdate(cartItem);
                return RedirectToAction("Index");
            }
            ViewBag.ProductId = repo.GetSelectList(cartItem);
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = repo.Find((int)id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartItem cartItem = repo.Find((int)id);
            repo.Delete(cartItem);           
            return RedirectToAction("Index");
        }

    }
}

GamerShop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GamerShop.Models;
using GamerShop.Repositories;

namespace GamerShop.Controllers
{
    public class ProductsController : Controller
    {
        private IProductRepository repo;

        public ProductsController(IProductRepository repo)
        {
            this.repo = repo;
        }


        // GET: Products
        public ActionResult Index(string searchText = "")
        {
            ViewBag.noContainer = true;
            return View(repo.FilterBy(searchText));
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = repo.Find((int)id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [Authorize(Roles = "Admin")]
        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Description,ImgUrl,Price,StockCount")] Product product)
        {
            if (ModelState.IsValid)
            {
                repo.AddOrUpdate(product);
                return RedirectToAction("Index");
            }

            return View(product);
        }

        [Authorize(Roles = "Admin")]
        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = repo.Find((int)id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [Authorize(Roles = "Admin")]
        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,ImgUrl,Price,StockCount")] Product product)
        {
            if (ModelState.IsValid)
            {
                repo.AddOrUpdate(product);
                return RedirectToAction("Index");
            }
            return View(product);
        }

        [Authorize(Roles = "Admin")]
        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = repo.Find((int)id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [Authorize(Roles = "Admin")]
        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = repo.Find((int)id);
            repo.Delete(product);
            return RedirectToAction("Index");
        }
    }
}

GamerShop/Views/Products/Create.cshtml
@model GamerShop.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImgUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImgUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImgUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StockCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StockCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StockCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GamerShop/Views/Products/Delete.cshtml
@model GamerShop.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StockCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StockCount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GamerShop/Views/Products/Details.cshtml
@model GamerShop.Models.Product

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-xs-12 col-md-6">
        <img src="@Html.DisplayTextFor(model => model.ImgUrl)" class="img-responsive product-img" alt="" />
        <div class="product-section">
            <h3>Product information</h3>
            <p>@Html.DisplayFor(model => model.Description)</p>
        </div>
    </div>
    <div class="col-xs-12 col-md-6">
        <h2>@Html.DisplayFor(model => model.Title)</h2>
        <h5>Product id = @Html.DisplayFor(model => model.Id)</h5>
        <h4>@Html.DisplayFor(model => model.Price)</h4>
        <p>
            <strong>Left in stock: </strong> @Html.DisplayFor(model => model.StockCount)
            <br />
            @using (Html.BeginForm("AddToCart", "CartItems", new { productId = Model.Id }, FormMethod.Post))
            {
                <input type="number" name="quantity" class="quantity text-center" value="1" min="1" max="@Html.DisplayTextFor(model => model.StockCount)" />
               //@Html.ActionLink("Add To Cart", "AddToCart", "CartItems", new { productId = Model.Id }, new { @class = "btn btn-primary btn-xl page-scroll" })
                <button class="btn btn-primary btn-x1 page-scroll" type="submit">
                    Add To Cart
                </button>
            
            }

        </p>
        <div class="product-section">
            <h3>Return and refund policy</h3>
            <p>
                I’m a Return and Refund policy.
                I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase.
                Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.
            </p>
        </div>
    </div>
</div>
<p>
    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) <text> | </text>
    }
    @Html.ActionLink("Back to List", "Index")
</p>

GamerShop/Views/Products/Edit.cshtml
@model GamerShop.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImgUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImgUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImgUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StockCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StockCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StockCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GamerShop/Views/Products/Index.cshtml
@model IEnumerable<GamerShop.Models.Product>

@{
    ViewBag.Title = "Index";
}

<div id="product-list-wrap">
    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        <p>@Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-xl" })</p>
    }

    @using (Html.BeginForm("Index", "Products"))
    {

        <div class="search-wrap">
            <input type="text" name="searchText" placeholder="Search..." class="search" required />
            <button class="btn btn-primary btn-x1" type="submit">
                <i class="fa fa-search fa-3x"></i>
            </button>
        </div>

    }

    <div class="grid js-masonry"
         data-masonry-options='{ "itemSelector": ".grid-item", "columnWidth": 340 }'>
        @foreach (var item in Model)
        {
            <div class="grid-item">
                <div class="product-wrap">
                    <img src="@Html.DisplayTextFor(modelItem => item.ImgUrl)" alt="">
                    <h1>@Html.DisplayFor(modelItem => item.Title)</h1>
                    <h4>@Html.DisplayNameFor(model => model.Price) @Html.DisplayFor(modelItem => item.Price)</h4>
                    <div class="product-details">
                        @Html.ActionLink("View Details", "Details", new { id = item.Id }, new { @class = "btn btn-product" })
                    </div>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <div class="product-details">
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-product" })
                        </div>
                        <div class="product-details">
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-product" })
                        </div>
                    }
                </div>
            </div>

        }
    </div>

</div>